"""Bots that carry out orders generated by a logistic regressor model."""
import logging

from abc import ABC
from dataclasses import dataclass
from pathlib import Path
from typing import List, Sequence

from diplomacy_research.players.benchmark_player import DipNetSLPlayerSession
from diplomacy.utils import strings as diplomacy_strings
from diplomacy.utils.constants import SuggestionType

from chiron_utils.bots.baseline_bot import BaselineBot, BotType

LOGGER = logging.getLogger(__name__)

MODEL_PATH = "saved_model/neurips2019-sl_model/000000009"

@dataclass
class DipnetBot(BaselineBot, ABC):
    """Bot based on dipnet.

    `MODEL_PATH` should point to folder containing model .pkl files.

    Each model corresponds to a (unit, location, phase) combination.

    Unit types are 'A', 'F'.

    Location types include all possible locations on the board, such as 'BRE', 'LON', 'STP_SC', etc.

    Phase types are 'SM', 'FM', 'WA, 'SR', 'FR', 'CD'
    """

    player_type = diplomacy_strings.NO_PRESS_BOT

    def __post_init__(self) -> None:
        """Verify that model path exists when instantiated."""
        super().__post_init__()
        self.model = DipNetSLPlayerSession(model_dir=MODEL_PATH)

    def get_orders(self) -> List[str]:
        """Get order predictions from model.

        Returns:
            List of predicted orders.
        """
        #state = self.game.get_state()
        orders_future = self.model.get_orders(self.game, self.power_name)
        orders: List[str] = orders_future.result()
        LOGGER.info("Orders to suggest: %s", orders)

        return orders

    async def gen_orders(self) -> List[str]:
        """Generate orders for a turn.

        Returns:
            List of orders to carry out.
        """
        orders = self.get_orders()
        if self.bot_type == BotType.ADVISOR:
            await self.suggest_orders(orders)
        elif self.bot_type == BotType.PLAYER:
            await self.send_orders(orders, wait=True)
        return orders

    async def do_messaging_round(self, orders: Sequence[str]) -> List[str]:
        """Carry out one round of messaging.

        Returns:
            List of orders to carry out.
        """
        return list(orders)


@dataclass
class DipnetAdvisor(DipnetBot):
    """Advisor form of `DipnetBot`."""

    bot_type = BotType.ADVISOR
    default_suggestion_type = SuggestionType.MOVE


@dataclass
class DipnetPlayer(DipnetBot):
    """Player form of `DipnetBot`."""

    bot_type = BotType.PLAYER
